require 'rake/clean'

INCLUDE = "contrib"

ERLC_FLAGS = "-I#{INCLUDE} +warn_unused_vars +warn_unused_import +debug_info "

SRC = FileList['src/*.erl']
OBJ = SRC.pathmap("%{ebin}X.beam")


CLEAN.include("ebin/*")

directory 'ebin'

rule ".beam" => ["%{ebin}X.erl"] do |t|
  sh "erlc -D EUNIT -pa ebin -W #{ERLC_FLAGS} -o ebin #{t.source}"
end

task :clean do
  sh "rm -rf ebin/*.beam"
end

task :compile => ['ebin'] + OBJ

task :copy do
#  sh "cp src/*.hrl ebin/"
#  sh "cp src/*.app ebin/"
end

task :default => [:compile, :copy]
